version: '3'
services:
  react:
    build:
      context: .
    ports:
      - "3000:3000"
    container_name: react-ui
    stdin_open: true
    volumes:
       - ./:/usr/src/app/
       - /usr/src/app/node_modules
    command: npm start

